# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 739776317d6fc968494fc3f53c6932f80467ea235ac87dbc040f0d1bee4abf03f5d03cc938604832e795b10e657f90c43a30e530d233303d958fc805e8e93513

test:
  secret_key_base: eac30269dab96e63c1b9f92e7177a312a09d265a8ff0c9823306ce57401a3ee57fdebe20da6ca8f446b7f4578485b812e77ff3d7a990f5b9c52e0f9db9903fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
